steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/kindred/paddleball:$_PR_NUMBER$_HEAD_BRANCH', '.' ]
  
images:
- 'gcr.io/$PROJECT_ID/kindred/paddleball:$_PR_NUMBER$_HEAD_BRANCH'