steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/kindred/paddleball:$_VERSION', '.' ]
  id: 'version'

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/kindred/paddleball:$_VERSION', 'gcr.io/$PROJECT_ID/kindred/paddleball']
  wait_for: ['version']
  id: 'latest'

steps:
- name: gcr.io/cloud-builders/docker
  args: ['bash', '-c', 'docker pull gcr.io/$PROJECT_ID/kindred/paddleball:$_VERSION && { echo "refusing to overwrite image!"; exit 1; } || echo "continuing, version of image not built yet"']

substitutions:
  _VERSION: '1.0.1' # manually update

images:
- 'gcr.io/$PROJECT_ID/kindred/paddleball:$_VERSION'
- 'gcr.io/$PROJECT_ID/kindred/paddleball'
