steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/kindred/paddleball:$_PR_NUMBER', '.' ]
substitutions:
  _PR_NUMBER: latest
images:
- 'gcr.io/$PROJECT_ID/kindred/paddleball:$_PR_NUMBER'