steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/kindred/paddleball:$_VERSION$_PR_NUMBER', '.' ]

substitutions:
  _VERSION: "1.0.0" # manually update

images:
- 'gcr.io/$PROJECT_ID/kindred/paddleball:$_VERSION$_PR_NUMBER'