#
# The number of pod replicas, keep mininum 2 for availability and zero downtime releases
#
replicaCount: 1

image:
  repository: gcr.io/public-registry-265316/kindred/paddleball
  tag: 1.0.3
  pullPolicy: IfNotPresent

owningTeam: PE

imagePullSecrets: []

#
# The listening ports of your component
#
service:
  type: NodePort
  port: 2222
  targetPort: 32222 

server:
  name: paddleball
  key: 1984

#
# Override the default capacity allocation for the container
#
resources:
  requests:
    cpu: 100m
    memory: 16M
  limits:
    cpu: 1
    memory: 16M