#
# The number of pod replicas, keep mininum 2 for availability and zero downtime releases
#
replicaCount: 1

image:
  repository: gcr.io/public-registry-265316/kindred/paddleball
  tag: 1.0.2
  pullPolicy: IfNotPresent

owningTeam: PE

imagePullSecrets: []

#
# The listening ports of your component
#
service:
  type: NodePort
  port: 2222
  targetPort: 32222 

server:
  name: paddleball
  key: 1984

#
# Override the default capacity allocation for the container
#
resources:
  requests:
    cpu: 100m
    memory: 16M
  limits:
    cpu: 1
    memory: 16M

#
# Override default liveness and readiness probes for the container
#
# livenessProbe:
#   httpGet:
#     path: /health
#     port: admin
#   initialDelaySeconds: 2
#   periodSeconds: 5
#   timeoutSeconds: 1
#   successThreshold: 1
#   failureThreshold: 3

# readinessProbe:
#   httpGet:
#     path: /health
#     port: admin
#   initialDelaySeconds: 1
#   periodSeconds: 5
#   timeoutSeconds: 1
#   successThreshold: 1
#   failureThreshold: 3